"use client";

import { Pattern, Scenario, Stock } from "@/lib/types";
import { Card, CardHeader } from "@/components/ui/Card";
import { ScenarioSimulator } from "@/components/ScenarioSimulator";
import { PatternCard } from "@/components/PatternCard";
import { RiskMeter } from "@/components/RiskMeter";
import { DayTradingSim } from "@/components/DayTradingSim";
import { useAICoach } from "@/lib/useAICoach";

export function AICoachPanel({
  stock,
  fallbackScenarios,
  fallbackPattern,
}: {
  stock: Stock;
  fallbackScenarios: Scenario[];
  fallbackPattern: Pattern;
}) {
  const { data, loading } = useAICoach(stock.ticker, fallbackScenarios, fallbackPattern);

  if (loading) {
    return (
      <Card>
        <CardHeader eyebrow={stock.ticker} title="AI Coach" />
        <div className="flex h-40 animate-pulse items-center justify-center text-sm text-ink-muted">
          Analyzing recent news, earnings and fundamentals…
        </div>
      </Card>
    );
  }

  const { scenarios, pattern, risk, source } = data;

  return (
    <div className="space-y-2">
      <ScenarioSimulator ticker={stock.ticker} scenarios={scenarios} price={stock.price} volatility={stock.volatility} />
      <DayTradingSim ticker={stock.ticker} price={stock.price} volatility={stock.volatility} scenarios={scenarios} />
      <div className="grid gap-6 lg:grid-cols-2">
        <PatternCard pattern={pattern} ticker={stock.ticker} />
        <RiskMeter stock={stock} ai={risk} />
      </div>
      <p className="text-[11px] text-ink-muted">
        Scenario predictions come from a trained ML model (see note above) — that part never depends on the AI call
        below.{" "}
        {source === "ai"
          ? "Pattern and risk analysis generated by AI from this stock's recent news, earnings and fundamentals."
          : "Pattern and risk are using baseline analysis — live AI analysis was unavailable."}
      </p>
    </div>
  );
}
