"use client";

import { useEffect, useState } from "react";
import { Pattern, Scenario, Stock } from "@/lib/types";
import { Card, CardHeader } from "@/components/ui/Card";
import { ScenarioSimulator } from "@/components/ScenarioSimulator";
import { PatternCard } from "@/components/PatternCard";
import { RiskMeter, AIRiskOverride } from "@/components/RiskMeter";

type CoachResponse = {
  scenarios: Scenario[];
  pattern: Pattern;
  risk: AIRiskOverride;
  source: "ai" | "fallback";
};

export function AICoachPanel({
  stock,
  fallbackScenarios,
  fallbackPattern,
}: {
  stock: Stock;
  fallbackScenarios: Scenario[];
  fallbackPattern: Pattern;
}) {
  const [data, setData] = useState<CoachResponse | null>(null);
  const [source, setSource] = useState<"ai" | "fallback">("fallback");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch(`/api/coach/${stock.ticker}`)
      .then((r) => r.json())
      .then((d) => {
        if (cancelled) return;
        const scenarios = Array.isArray(d.scenarios) && d.scenarios.length === 3 ? d.scenarios : fallbackScenarios;
        const pattern = d.pattern ?? fallbackPattern;
        const risk = d.risk ?? null;
        setData({ scenarios, pattern, risk, source: d.source === "ai" ? "ai" : "fallback" });
        setSource(d.source === "ai" ? "ai" : "fallback");
      })
      .catch(() => {
        if (cancelled) return;
        setData({ scenarios: fallbackScenarios, pattern: fallbackPattern, risk: null as never, source: "fallback" });
        setSource("fallback");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stock.ticker]);

  if (loading) {
    return (
      <Card>
        <CardHeader eyebrow={stock.ticker} title="AI Coach" />
        <div className="flex h-40 animate-pulse items-center justify-center text-sm text-ink-muted">
          Analyzing recent news, earnings and fundamentals…
        </div>
      </Card>
    );
  }

  const scenarios = data?.scenarios ?? fallbackScenarios;
  const pattern = data?.pattern ?? fallbackPattern;
  const risk = data?.risk ?? undefined;

  return (
    <div className="space-y-2">
      <ScenarioSimulator ticker={stock.ticker} scenarios={scenarios} price={stock.price} volatility={stock.volatility} />
      <div className="grid gap-6 lg:grid-cols-2">
        <PatternCard pattern={pattern} ticker={stock.ticker} />
        <RiskMeter stock={stock} ai={risk} />
      </div>
      <p className="text-[11px] text-ink-muted">
        {source === "ai"
          ? "Prediction, pattern and risk analysis generated by Claude from this stock's recent news, earnings and fundamentals."
          : "Using baseline analysis — live AI analysis was unavailable."}
      </p>
    </div>
  );
}
