"use client";

import { useEffect, useState } from "react";
import { Scenario } from "@/lib/types";
import { Card, CardHeader } from "@/components/ui/Card";
import { ScenarioSimulator } from "@/components/ScenarioSimulator";

export function AIScenarioSimulator({
  ticker,
  price,
  volatility,
  fallbackScenarios,
}: {
  ticker: string;
  price: number;
  volatility: number;
  fallbackScenarios: Scenario[];
}) {
  const [scenarios, setScenarios] = useState<Scenario[] | null>(null);
  const [source, setSource] = useState<"ai" | "fallback">("fallback");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch(`/api/predict/${ticker}`)
      .then((r) => r.json())
      .then((d) => {
        if (cancelled) return;
        setScenarios(Array.isArray(d.scenarios) && d.scenarios.length === 3 ? d.scenarios : fallbackScenarios);
        setSource(d.source === "ai" ? "ai" : "fallback");
      })
      .catch(() => {
        if (cancelled) return;
        setScenarios(fallbackScenarios);
        setSource("fallback");
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [ticker]);

  if (loading) {
    return (
      <Card>
        <CardHeader eyebrow={ticker} title="Prediction Simulator" />
        <div className="flex h-40 animate-pulse items-center justify-center text-sm text-ink-muted">
          Analyzing recent news, earnings and fundamentals…
        </div>
      </Card>
    );
  }

  return (
    <div className="space-y-2">
      <ScenarioSimulator ticker={ticker} scenarios={scenarios ?? fallbackScenarios} price={price} volatility={volatility} />
      <p className="text-[11px] text-ink-muted">
        {source === "ai"
          ? "Scenarios generated by Claude from this stock's recent news, earnings and fundamentals."
          : "Using baseline scenarios — live AI analysis was unavailable."}
      </p>
    </div>
  );
}
